#!/usr/bin/env python3
"""Exercise installed static tools with generated fixtures; never execute an APK."""
# BEGIN ANDROID WORKBENCH ENTRY
if __name__ == '__main__':
    import sys as _awb_sys
    from pathlib import Path as _AwbPath
    _awb_project = None
    for _awb_origin in (_AwbPath.cwd(),):
        for _awb_root in (_awb_origin, *_awb_origin.parents):
            if (_awb_root / 'workbench.project.json').is_file():
                _awb_project = _awb_root
                break
        if _awb_project is not None:
            break
    if _awb_project is not None:
        import json as _awb_json
        _awb_config = _awb_json.loads((_awb_project / 'workbench.project.json').read_text())
        _awb_runtime = (_awb_project / _awb_config.get('workbench_root', 'android-workbench')).resolve()
        if not (_awb_runtime / 'workbench/bridge.py').is_file():
            raise SystemExit('Android Workbench runtime missing; managed entry cannot run directly')
        _awb_sys.path.insert(0, str(_awb_runtime))
        from workbench.bridge import entry as _awb_entry
        _awb_entry(__file__)
# END ANDROID WORKBENCH ENTRY

import argparse
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import uuid
import zipfile

MARKER = 'ANDROID_STATIC_ENV_SMOKE'


def sha256(path):
    h = hashlib.sha256()
    with path.open('rb') as f:
        for block in iter(lambda: f.read(1024 * 1024), b''):
            h.update(block)
    return h.hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--workspace', default='.')
    parser.add_argument('--apk', type=Path, help='Optional authorized APK; analyzed read-only')
    parser.add_argument('--source', help='Provenance for --apk, such as export record or upstream URL')
    parser.add_argument('--so', type=Path, help='Optional ELF shared library for native smoke tests')
    parser.add_argument('--so-source', help='Provenance for --so')
    parser.add_argument('--so-symbol', help='Exported function to disassemble (sets ARM/Thumb mode from its value)')
    args = parser.parse_args()
    if args.so and not args.so_source:
        parser.error('--so requires --so-source')
    if args.apk and not args.source:
        parser.error('--apk requires --source so provenance is recorded before parsing')
    workspace = Path(args.workspace).resolve()
    root = workspace / '.android-static'
    manifest = json.loads((root / 'manifest.json').read_text())
    selected = set(manifest['selected'])
    if 'smali' not in selected or manifest['results']['smali']['status'] != 'verified':
        parser.error('A verified smali installation is required to generate the DEX fixture')
    out = workspace / 'evidence/android-static' / ('smoke-' + dt.datetime.now(dt.timezone.utc).strftime('%Y%m%dT%H%M%SZ') + '-' + uuid.uuid4().hex[:6])
    out.mkdir(parents=True)
    env = dict(os.environ, SEMGREP_SEND_METRICS='off', SEMGREP_ENABLE_VERSION_CHECK='0', PYTHONNOUSERSITE='1',
               XDG_CONFIG_HOME=str(root / 'config'), XDG_CACHE_HOME=str(root / 'cache/xdg'))
    env.pop('PYTHONPATH', None)
    env.pop('PYTHONHOME', None)
    # Wrappers activate the project-local toolchain without evaluating the user's .envrc.
    java_home = json.loads((root / 'state/jdk.json').read_text())['java_home']
    env['JAVA_HOME'] = java_home
    env['PATH'] = os.pathsep.join([str(root / 'bin'), str(Path(java_home) / 'bin')]) + os.pathsep + env.get('PATH', '')
    records = []
    provenance = {'fixture': 'Generated by android-static-env/scripts/smoke.py', 'marker': MARKER}
    if args.apk:
        args.apk = args.apk.expanduser().resolve(strict=True)
        provenance['apk'] = {'path': str(args.apk), 'sha256': sha256(args.apk), 'source': args.source}
    (out / 'inputs.json').write_text(json.dumps(provenance, indent=2, ensure_ascii=False) + '\n')

    def run(name, argv, validate=None, timeout=180):
        log = out / (name + '.log')
        command = list(map(str, argv))
        stderr_log = out / (name + '.stderr.log')
        with log.open('w') as f, stderr_log.open('w') as err:
            f.write(json.dumps(command) + '\n')
            f.flush()
            result = subprocess.run(command, env=env, stdin=subprocess.DEVNULL, stdout=f, stderr=err, text=True, timeout=timeout, cwd=out)
        output = log.read_text(errors='replace').split('\n', 1)[1]
        if name == 'ghidra-headless-import':
            output += stderr_log.read_text(errors='replace')
        if result.returncode:
            raise RuntimeError(f'{name}: exit {result.returncode}; {log}')
        if validate:
            validate(output)
        return {'name': name, 'status': 'passed', 'argv': command, 'log': str(log), 'stderr_log': str(stderr_log)}

    def require(condition, message):
        if not condition:
            raise RuntimeError(message)

    def attempt(name, function):
        try:
            result = function()
            records.append(result or {'name': name, 'status': 'passed'})
            print('OK ' + name, flush=True)
        except (OSError, RuntimeError, ValueError, subprocess.SubprocessError, AssertionError, KeyError, TypeError) as error:
            records.append({'name': name, 'status': 'failed', 'error': str(error)})
            print('FAIL ' + name + ': ' + str(error), file=sys.stderr, flush=True)

    smali = out / 'smali-src'
    smali.mkdir()
    (smali / 'Probe.smali').write_text('.class public Lskill/smoke/Probe;\n.super Ljava/lang/Object;\n\n.method public static marker()Ljava/lang/String;\n    .registers 1\n    const-string v0, "' + MARKER + '"\n    return-object v0\n.end method\n')
    dex = out / 'classes.dex'
    attempt('smali-assemble', lambda: run('smali-assemble', ['smali', 'assemble', smali, '-o', dex], lambda _: require(dex.read_bytes().startswith(b'dex\n'), 'Not a DEX file')))
    if dex.exists():
        provenance['dex_sha256'] = sha256(dex)
        attempt('baksmali-disassemble', lambda: run('baksmali-disassemble', ['baksmali', 'disassemble', dex, '-o', out / 'smali-out'], lambda _: require(any(MARKER in p.read_text() for p in (out / 'smali-out').rglob('*.smali')), 'Smali marker missing')))
        if 'sdk' in selected:
            attempt('sdk-dex-checksum', lambda: run('sdk-dex-checksum', [root / 'sdk/build-tools/36.0.0/dexdump', '-c', dex]))
        if 'jadx' in selected:
            attempt('jadx-decompile', lambda: run('jadx-decompile', ['jadx', '--no-res', '-d', out / 'jadx', dex], lambda _: require(any(MARKER in p.read_text() for p in (out / 'jadx').rglob('*.java')), 'Decompiled marker missing')))
        if 'dex2jar' in selected:
            jar = out / 'classes.jar'
            def verify_jar(_):
                with zipfile.ZipFile(jar) as z:
                    require('skill/smoke/Probe.class' in z.namelist(), 'Converted class missing')
            attempt('dex2jar-convert', lambda: run('dex2jar-convert', ['d2j-dex2jar', '-o', jar, dex], verify_jar))
        if 'androguard' in selected:
            code = 'from androguard.core.dex import DEX; import sys; d=DEX(open(sys.argv[1],"rb").read()); assert "Lskill/smoke/Probe;" in d.get_classes_names(); print("DEX class parsed")'
            attempt('androguard-parse', lambda: run('androguard-parse', ['androguard-python', '-c', code, dex]))
        if 'droidasc' in selected:
            droidasc_apk = out / 'droidasc-fixture.apk'
            with zipfile.ZipFile(droidasc_apk, 'w') as package:
                package.write(dex, 'classes.dex')
            attempt('droidasc-listclass', lambda: run('droidasc-listclass', ['droidasc', 'listclass', droidasc_apk], lambda t: require('Lskill/smoke/Probe;' in t, 'Droid ASC class missing')))
            attempt('droidasc-findrefs', lambda: run('droidasc-findrefs', ['droidasc', 'findrefs', droidasc_apk, 'string', MARKER], lambda t: require(MARKER in t and '->marker' in t, 'Droid ASC marker reference missing')))
            attempt('droidasc-getclass', lambda: run('droidasc-getclass', ['droidasc', 'getclass', droidasc_apk, 'Lskill/smoke/Probe;'], lambda t: require('class Probe' in t and MARKER in t, 'Droid ASC decompiled marker missing')))
        if 'apkid' in selected:
            def verify_apkid(output):
                data = json.loads(output)
                require(bool(data.get('files')), 'APKiD returned no file records')
            attempt('apkid-dex', lambda: run('apkid-dex', ['apkid', '-j', dex], verify_apkid))
        if 'utilities' in selected:
            rule = out / 'fixture.yar'
            rule.write_text('rule static_env_fixture { strings: $m = "' + MARKER + '" condition: uint32(0) == 0x0a786564 and $m }\n')
            attempt('yara-match', lambda: run('yara-match', ['yara', rule, dex], lambda t: require('static_env_fixture' in t, 'YARA did not match its known fixture')))
    if 'semgrep' in selected:
        java = out / 'Probe.java'
        java.write_text('import android.util.Log;\nclass Probe { void probe() { Log.d("fixture", "' + MARKER + '"); } }\n')
        config = out / 'fixture-semgrep.yaml'
        config.write_text('rules:\n  - id: android-static-fixture\n    languages: [java]\n    severity: INFO\n    message: Known smoke fixture\n    pattern: Log.d(...)\n')
        attempt('semgrep-match', lambda: run('semgrep-match', ['semgrep', 'scan', '--config', config, '--metrics=off', '--disable-version-check', '--no-git-ignore', '--json', '--output', out / 'semgrep.json', java], lambda _: require(bool(json.loads((out / 'semgrep.json').read_text())['results']), 'Semgrep did not match its known fixture')))
    native = args.so.expanduser().resolve(strict=True) if args.so else Path('/usr/bin/true')
    provenance['native'] = {'path': str(native), 'sha256': sha256(native), 'source': args.so_source if args.so else 'Host /usr/bin/true (ELF executable, not an Android shared library)'}
    (out / 'inputs.json').write_text(json.dumps(provenance, indent=2, ensure_ascii=False) + '\n')
    if 'native-python' in selected:
        native_args = ['so-info', native, '--source', provenance['native']['source'], '--output', out / 'so-info.json']
        if args.so_symbol:
            native_args += ['--symbol', args.so_symbol]
        attempt('native-python-elf', lambda: run('native-python-elf', native_args, lambda _: require(json.loads((out / 'so-info.json').read_text())['sha256'] == provenance['native']['sha256'], 'ELF hash mismatch')))
    if 'utilities' in selected:
        attempt('native-readelf', lambda: run('native-readelf', ['readelf', '-h', '-l', '-d', '-Ws', native]))
        attempt('native-llvm', lambda: run('native-llvm', ['llvm-objdump', '-d', native]))
        attempt('native-checksec', lambda: run('native-checksec', ['checksec', '--file=' + str(native)]))
    if 'rizin' in selected:
        attempt('rizin-elf', lambda: run('rizin-elf', ['rz-bin', '-Ij', native], lambda t: require(json.loads(t).get('info', json.loads(t)).get('class', '').startswith('ELF'), 'Rizin did not recognize ELF')))
    if 'ghidra' in selected:
        projects = out / 'ghidra-projects'
        projects.mkdir()
        attempt('ghidra-headless-import', lambda: run('ghidra-headless-import', ['analyzeHeadless', projects, 'Smoke', '-import', native, '-analysisTimeoutPerFile', '60', '-max-cpu', '2', '-deleteProject'], lambda t: require('Analysis succeeded' in t, 'Ghidra did not report successful analysis'), timeout=240))
    if args.apk:
        apk = args.apk
        if 'sdk' in selected:
            sdk = root / 'sdk'
            attempt('apk-manifest', lambda: run('apk-manifest', [root / 'bin/apkanalyzer', 'manifest', 'print', apk], lambda t: require('<manifest' in t, 'Manifest XML missing')))
            attempt('apk-signature', lambda: run('apk-signature', [sdk / 'build-tools/36.0.0/apksigner', 'verify', '--verbose', '--print-certs', apk]))
        if 'apktool' in selected:
            attempt('apktool-decode', lambda: run('apktool-decode', ['apktool', 'd', '-p', out / 'framework', '-o', out / 'apktool', apk], timeout=300))
        if 'quark' in selected:
            rules = (root / 'quark-rules.path').read_text().strip()
            attempt('quark-apk', lambda: run('quark-apk', ['quark', '-a', apk, '-r', rules, '-o', out / 'quark.json'], timeout=300))
        require(sha256(apk) == provenance['apk']['sha256'], 'Input APK changed during smoke tests')
    elif 'quark' in selected:
        records.append({'name': 'quark-apk', 'status': 'not-tested', 'reason': 'No APK provided; engine CLI and pinned rule presence are checked by setup.py'})
    require(sha256(native) == provenance['native']['sha256'], 'Input ELF changed during smoke tests')
    (out / 'inputs.json').write_text(json.dumps(provenance, indent=2, ensure_ascii=False) + '\n')
    report = {'timestamp_utc': dt.datetime.now(dt.timezone.utc).isoformat(), 'provenance': provenance, 'results': records,
              'not_covered': ['GUI display and interaction', 'MobSF service startup', 'arbitrary APK compatibility', 'AAB/APKS transformation']}
    (out / 'smoke-report.json').write_text(json.dumps(report, ensure_ascii=False, indent=2) + '\n')
    print('Report: ' + str(out / 'smoke-report.json'))
    return int(any(item['status'] == 'failed' for item in records))


if __name__ == '__main__':
    sys.exit(main())
